interface Env { ASSETS: Fetcher; DB: D1Database; LOG_API_KEY?: string; ADMIN_EMAIL?: string; ADMIN_PASSWORD?: string; JWT_SECRET?: string }
type LogLevel = "debug" | "info" | "warn" | "error" | "fatal";
const H = { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" };
const json = (data: unknown, status = 200) => new Response(JSON.stringify(data), { status, headers: H });
const validLevel = (v: unknown): v is LogLevel => ["debug", "info", "warn", "error", "fatal"].includes(String(v));
function auth(req: Request, env: Env) { if (!env.LOG_API_KEY) return false; const h=req.headers.get("authorization"); const key=h?.startsWith("Bearer ")?h.slice(7).trim():req.headers.get("x-api-key")?.trim(); return key!==env.LOG_API_KEY; }
function map(row: Record<string, unknown>) { let metadata=null; if(row.metadata) try{metadata=JSON.parse(String(row.metadata))}catch{} return {...row,id:String(row.id),level:String(row.level),source:row.source==null?null:String(row.source),metadata}; }
function b64url(data: ArrayBuffer | string) { const bytes=typeof data==='string'?new TextEncoder().encode(data):new Uint8Array(data); let s=''; for(const b of bytes)s+=String.fromCharCode(b); return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
async function signJwt(payload: Record<string,unknown>, secret: string) { const enc=b64url(JSON.stringify({alg:'HS256',typ:'JWT'}))+'.'+b64url(JSON.stringify(payload)); const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']); const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(enc)); return enc+'.'+b64url(sig); }
async function verifyJwt(token: string, secret: string) { try { const [h,p,s]=token.split('.'); if(!h||!p||!s)return null; const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']); const raw=s.replace(/-/g,'+').replace(/_/g,'/'); const pad=raw+'='.repeat((4-raw.length%4)%4); const sig=Uint8Array.from(atob(pad),c=>c.charCodeAt(0)); const ok=await crypto.subtle.verify('HMAC',key,sig,new TextEncoder().encode(h+'.'+p)); if(!ok)return null; const bp=p.replace(/-/g,'+').replace(/_/g,'/'); return JSON.parse(atob(bp+'='.repeat((4-bp.length%4)%4))); } catch{return null;} }
async function adminLogin(req: Request, env: Env) { if(!env.ADMIN_EMAIL||!env.ADMIN_PASSWORD||!env.JWT_SECRET)return json({success:false,error:'Admin authentication is not configured on this deployment. Add ADMIN_EMAIL, ADMIN_PASSWORD and JWT_SECRET as Cloudflare secrets.'},503); let x:any;try{x=await req.json()}catch{return json({success:false,error:'Invalid JSON body'},400)} const email=typeof x?.email==='string'?x.email.trim().toLowerCase():''; const password=typeof x?.password==='string'?x.password:''; if(!email||!password)return json({success:false,error:'Missing email or password'},400); if(email!==env.ADMIN_EMAIL.trim().toLowerCase()||password!==env.ADMIN_PASSWORD)return json({success:false,error:'Invalid email or password'},401); const user={id:'super-admin-1',email:env.ADMIN_EMAIL.trim().toLowerCase(),name:'Logify Super Admin',role:'super_admin',status:'active'}; const token=await signJwt({id:user.id,email:user.email,role:user.role,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+7*86400},env.JWT_SECRET); return json({user,token}); }
async function verifySession(req: Request, env: Env) { if(!env.JWT_SECRET)return json({valid:false,error:'Admin authentication is not configured.'},503); const h=req.headers.get('authorization'); if(!h?.startsWith('Bearer '))return json({valid:false,error:'Missing authorization token'},401); const p=await verifyJwt(h.slice(7).trim(),env.JWT_SECRET); if(!p||p.role!=='super_admin'||(p.exp&&Number(p.exp)<Date.now()/1000))return json({valid:false,error:'Invalid or expired token'},401); return json({valid:true,user:{id:p.id,email:p.email,name:'Logify Super Admin',role:'super_admin',status:'active'}}); }
async function handle(req: Request, env: Env) {
 const u=new URL(req.url), p=u.pathname.split("/").filter(Boolean), id=p.length===3?p[2]:null;
 if(p.join('/')==='api/auth/login'&&req.method==='POST')return adminLogin(req,env);
 if(p.join('/')==='api/auth/verify-session'&&req.method==='GET')return verifySession(req,env);
 if(p.join('/')==='api/logs' || p[0]==='api'&&p[1]==='logs'){if(auth(req,env)) return json({success:false,error:"Unauthorized"},401);
 if(req.method==="GET") { if(id){const r=await env.DB.prepare("SELECT * FROM logs WHERE id=?").bind(id).first<Record<string,unknown>>();return r?json({success:true,log:map(r)}):json({success:false,error:"Log not found"},404)} const limit=Math.min(Math.max(Number(u.searchParams.get("limit")||50),1),200),offset=Math.max(Number(u.searchParams.get("offset")||0),0),f:string[]=[],b:unknown[]=[]; const level=u.searchParams.get("level"),source=u.searchParams.get("source"),q=u.searchParams.get("q"); if(level){f.push("level=?");b.push(level)} if(source){f.push("source=?");b.push(source)} if(q){f.push("message LIKE ?");b.push(`%${q}%`)} const w=f.length?` WHERE ${f.join(" AND ")}`:""; const r=await env.DB.prepare(`SELECT * FROM logs${w} ORDER BY created_at DESC LIMIT ? OFFSET ?`).bind(...b,limit,offset).all(); const c=await env.DB.prepare(`SELECT COUNT(*) count FROM logs${w}`).bind(...b).first<{count:number}>(); return json({success:true,logs:(r.results||[]).map(map),total:Number(c?.count||0),limit,offset}); }
 if(req.method==="POST"&&!id){let x:any;try{x=await req.json()}catch{return json({success:false,error:"Invalid JSON body"},400)} const msg=typeof x?.message==="string"?x.message.trim():""; if(!validLevel(x?.level)||!msg||msg.length>10000)return json({success:false,error:"Invalid level or message"},400); if(x.metadata!==undefined&&x.metadata!==null&&(typeof x.metadata!=="object"||Array.isArray(x.metadata)))return json({success:false,error:"metadata must be a JSON object"},400); const now=new Date().toISOString(),lid=crypto.randomUUID(); await env.DB.prepare("INSERT INTO logs (id,level,message,source,metadata,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").bind(lid,x.level,msg,x.source==null?null:String(x.source).trim(),x.metadata==null?null:JSON.stringify(x.metadata),now,now).run(); const r=await env.DB.prepare("SELECT * FROM logs WHERE id=?").bind(lid).first<Record<string,unknown>>(); return json({success:true,log:map(r!)},201); }
 if(req.method==="PUT"&&id){const old=await env.DB.prepare("SELECT * FROM logs WHERE id=?").bind(id).first<Record<string,unknown>>();if(!old)return json({success:false,error:"Log not found"},404);let x:any;try{x=await req.json()}catch{return json({success:false,error:"Invalid JSON body"},400)} const level=x.level===undefined?old.level:x.level,msg=x.message===undefined?String(old.message):String(x.message).trim();if(!validLevel(level)||!msg||msg.length>10000)return json({success:false,error:"Invalid level or message"},400);let meta=old.metadata==null?null:String(old.metadata);if(x.metadata!==undefined){if(x.metadata!==null&&(typeof x.metadata!=="object"||Array.isArray(x.metadata)))return json({success:false,error:"metadata must be a JSON object"},400);meta=x.metadata==null?null:JSON.stringify(x.metadata)} await env.DB.prepare("UPDATE logs SET level=?,message=?,source=?,metadata=?,updated_at=? WHERE id=?").bind(level,msg,x.source===undefined?old.source:x.source==null?null:String(x.source).trim(),meta,new Date().toISOString(),id).run();const r=await env.DB.prepare("SELECT * FROM logs WHERE id=?").bind(id).first<Record<string,unknown>>();return json({success:true,log:map(r!)}); }
 if(req.method==="DELETE"){if(id){const r=await env.DB.prepare("DELETE FROM logs WHERE id=?").bind(id).run();return r.meta.changes?json({success:true,deleted:id}):json({success:false,error:"Log not found"},404)} await env.DB.prepare("DELETE FROM logs").run();return json({success:true,message:"All logs deleted"})}
 return json({success:false,error:"Method not allowed"},405);}
 return env.ASSETS.fetch(req);
}
export default { async fetch(req: Request, env: Env){try{return await handle(req,env)}catch(e){console.error(e);return json({success:false,error:'Internal server error'},500)}} };