interface Env { ASSETS: Fetcher; DB: D1Database; LOG_API_KEY?: string }
type LogLevel = "debug" | "info" | "warn" | "error" | "fatal";
const H = { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" };
const json = (data: unknown, status = 200) => new Response(JSON.stringify(data), { status, headers: H });
const validLevel = (v: unknown): v is LogLevel => ["debug", "info", "warn", "error", "fatal"].includes(String(v));
function auth(req: Request, env: Env) { if (!env.LOG_API_KEY) return false; const h=req.headers.get("authorization"); const key=h?.startsWith("Bearer ")?h.slice(7).trim():req.headers.get("x-api-key")?.trim(); return key!==env.LOG_API_KEY; }
function map(row: Record<string, unknown>) { let metadata=null; if(row.metadata) try{metadata=JSON.parse(String(row.metadata))}catch{} return {...row,id:String(row.id),level:String(row.level),source:row.source==null?null:String(row.source),metadata}; }
async function handle(req: Request, env: Env) {
 if(auth(req,env)) return json({success:false,error:"Unauthorized"},401);
 const u=new URL(req.url), p=u.pathname.split("/").filter(Boolean), id=p.length===3?p[2]:null;
 if(req.method==="GET") { if(id){const r=await env.DB.prepare("SELECT * FROM logs WHERE id=?").bind(id).first<Record<string,unknown>>();return r?json({success:true,log:map(r)}):json({success:false,error:"Log not found"},404)} const limit=Math.min(Math.max(Number(u.searchParams.get("limit")||50),1),200),offset=Math.max(Number(u.searchParams.get("offset")||0),0),f:string[]=[],b:unknown[]=[]; const level=u.searchParams.get("level"),source=u.searchParams.get("source"),q=u.searchParams.get("q"); if(level){f.push("level=?");b.push(level)} if(source){f.push("source=?");b.push(source)} if(q){f.push("message LIKE ?");b.push(`%${q}%`)} const w=f.length?` WHERE ${f.join(" AND ")}`:""; const r=await env.DB.prepare(`SELECT * FROM logs${w} ORDER BY created_at DESC LIMIT ? OFFSET ?`).bind(...b,limit,offset).all(); const c=await env.DB.prepare(`SELECT COUNT(*) count FROM logs${w}`).bind(...b).first<{count:number}>(); return json({success:true,logs:(r.results||[]).map(map),total:Number(c?.count||0),limit,offset}); }
 if(req.method==="POST"&&!id){let x:any;try{x=await req.json()}catch{return json({success:false,error:"Invalid JSON body"},400)} const msg=typeof x?.message==="string"?x.message.trim():""; if(!validLevel(x?.level)||!msg||msg.length>10000)return json({success:false,error:"Invalid level or message"},400); if(x.metadata!==undefined&&x.metadata!==null&&(typeof x.metadata!=="object"||Array.isArray(x.metadata)))return json({success:false,error:"metadata must be a JSON object"},400); const now=new Date().toISOString(),lid=crypto.randomUUID(); await env.DB.prepare("INSERT INTO logs (id,level,message,source,metadata,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").bind(lid,x.level,msg,x.source==null?null:String(x.source).trim(),x.metadata==null?null:JSON.stringify(x.metadata),now,now).run(); const r=await env.DB.prepare("SELECT * FROM logs WHERE id=?").bind(lid).first<Record<string,unknown>>(); return json({success:true,log:map(r!)},201); }
 if(req.method==="PUT"&&id){const old=await env.DB.prepare("SELECT * FROM logs WHERE id=?").bind(id).first<Record<string,unknown>>();if(!old)return json({success:false,error:"Log not found"},404);let x:any;try{x=await req.json()}catch{return json({success:false,error:"Invalid JSON body"},400)} const level=x.level===undefined?old.level:x.level,msg=x.message===undefined?String(old.message):String(x.message).trim();if(!validLevel(level)||!msg||msg.length>10000)return json({success:false,error:"Invalid level or message"},400);let meta=old.metadata==null?null:String(old.metadata);if(x.metadata!==undefined){if(x.metadata!==null&&(typeof x.metadata!=="object"||Array.isArray(x.metadata)))return json({success:false,error:"metadata must be a JSON object"},400);meta=x.metadata==null?null:JSON.stringify(x.metadata)} await env.DB.prepare("UPDATE logs SET level=?,message=?,source=?,metadata=?,updated_at=? WHERE id=?").bind(level,msg,x.source===undefined?old.source:x.source==null?null:String(x.source).trim(),meta,new Date().toISOString(),id).run();const r=await env.DB.prepare("SELECT * FROM logs WHERE id=?").bind(id).first<Record<string,unknown>>();return json({success:true,log:map(r!)}); }
 if(req.method==="DELETE"){if(id){const r=await env.DB.prepare("DELETE FROM logs WHERE id=?").bind(id).run();return r.meta.changes?json({success:true,deleted:id}):json({success:false,error:"Log not found"},404)} await env.DB.prepare("DELETE FROM logs").run();return json({success:true,message:"All logs deleted"})}
 return json({success:false,error:"Method not allowed"},405);
}
export default { async fetch(req: Request, env: Env){const p=new URL(req.url).pathname;if(p==="/api/logs"||p.startsWith("/api/logs/")){try{return await handle(req,env)}catch(e){console.error(e);return json({success:false,error:"Internal server error"},500)}}return env.ASSETS.fetch(req)} };
