import React, { useState, useEffect } from 'react';
import { Mail, Phone, MapPin, Send, HelpCircle, ShieldCheck, Ship, Plane, Truck, Warehouse, Lock, ArrowRight, Loader2 } from 'lucide-react';
import Navbar from './components/Navbar.tsx';
import Footer from './components/Footer.tsx';
import Hero from './components/Hero.tsx';
import TrustCenter from './components/TrustCenter.tsx';
import PublicTracker from './components/PublicTracker.tsx';
import QuoteCalculator from './components/QuoteCalculator.tsx';
import AdminPanel from './components/AdminPanel.tsx';
import PublicLiveChat from './components/PublicLiveChat.tsx';
import SendPackagePage from './components/pages/SendPackagePage.tsx';
import PricingPage from './components/pages/PricingPage.tsx';
import AboutPage from './components/pages/AboutPage.tsx';
import AdminLogin from './pages/AdminLogin.tsx';
import { User, Settings } from './types.js';

export default function App() {
  const [view, setView] = useState<string>('home');
  const [trackId, setTrackId] = useState<string>('');
  const [token, setToken] = useState<string | null>(() => { try { const stored=localStorage.getItem('logify_token'); if(stored)return stored; const m=document.cookie.match(/(^|;)\s*logify_token\s*=\s*([^;]+)/); if(m){const decoded=decodeURIComponent(m[2]);localStorage.setItem('logify_token',decoded);return decoded;} } catch(e){console.warn('Failed to retrieve authentication token:',e)} return null; });
  const [user, setUser] = useState<User | null>(null);
  const [authLoading, setAuthLoading] = useState(false);
  const [settings, setSettings] = useState<Settings>({companyName:'Logify Logistics',contactEmail:'operations@logify.com',contactPhone:'+1 (800) 555-LOGI',pricing:{basePrice:15,pricePerKg:2.5,pricePerKm:.15}});
  const [theme, setTheme] = useState<'light'|'dark'>(()=>{try{const s=localStorage.getItem('logify_theme');if(s==='dark'||s==='light')return s as 'light'|'dark';if(typeof window!=='undefined'&&window.matchMedia?.('(prefers-color-scheme: dark)').matches)return'dark'}catch(e){}return'light'});
  useEffect(()=>{document.documentElement.classList.toggle('dark',theme==='dark');try{localStorage.setItem('logify_theme',theme)}catch(e){}},[theme]);
  const toggleTheme=()=>setTheme(p=>p==='light'?'dark':'light');
  useEffect(()=>{fetch('/api/settings').then(r=>r.ok?r.json():Promise.reject()).then(setSettings).catch(()=>{})},[]);

  const fetchProfile=async(authToken:string)=>{setAuthLoading(true);try{const r=await fetch('/api/auth/verify-session',{headers:{Authorization:`Bearer ${authToken}`}});const d=await r.json();if(r.ok&&d?.valid&&d?.user?.role==='super_admin'&&d.user.email?.trim().toLowerCase()==='owighoyotaemmanuel424@gmail.com'){setUser(d.user);return}handleLogout(true)}catch(e){handleLogout(true)}finally{setAuthLoading(false)}};
  const syncViewWithLocation=()=>{const path=window.location.pathname;if(path==='/'||path==='/home')setView('home');else if(path==='/track'||path==='/tracking')setView('track');else if(path==='/send')setView('send');else if(path==='/pricing')setView('pricing');else if(path==='/about')setView('about');else if(path==='/contact')setView('contact');else if(path==='/secure-admin-portal-9x7k')setView('auth');else if(['/login','/register','/auth','/admin-login','/admin/login'].includes(path)){window.history.replaceState(null,'','/');setView('home')}else if(path==='/admin'||path==='/admin/dashboard'||path.startsWith('/admin/')){const stored=localStorage.getItem('logify_token');if(!stored){window.history.replaceState(null,'','/secure-admin-portal-9x7k');setView('auth')}else setView('admin')}else setView('home')};
  useEffect(()=>{if(token)fetchProfile(token);syncViewWithLocation();const h=()=>syncViewWithLocation();window.addEventListener('popstate',h);return()=>window.removeEventListener('popstate',h)},[token]);
  const handleLoginSuccess=(authToken:string,loggedUser:User)=>{try{localStorage.setItem('logify_token',authToken);const expires=new Date(Date.now()+7*864e5).toUTCString();document.cookie=`logify_token=${encodeURIComponent(authToken)}; expires=${expires}; path=/; SameSite=Lax; Secure`}catch(e){}setToken(authToken);setUser(loggedUser);window.history.pushState(null,'','/admin/dashboard');setView('admin')};
  function handleLogout(expired=false){try{localStorage.removeItem('logify_token');document.cookie='logify_token=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/; SameSite=Lax; Secure'}catch(e){}setToken(null);setUser(null);const path=expired?'/secure-admin-portal-9x7k?expired=true':'/secure-admin-portal-9x7k';window.history.pushState(null,'',path);setView('auth')}
  const handleNavigate=(newView:string)=>{let path='/';if(newView==='track'||newView==='tracking')path='/track';else if(newView==='send')path='/send';else if(newView==='pricing')path='/pricing';else if(newView==='about')path='/about';else if(newView==='contact')path='/contact';else if(newView==='auth')path='/secure-admin-portal-9x7k';else if(newView==='admin'){if(!token){path='/secure-admin-portal-9x7k';newView='auth'}else path='/admin/dashboard'}else if(newView!=='home')path='/'+newView;window.history.pushState(null,'',path);setView(newView);window.scrollTo({top:0,behavior:'smooth'})};

  function ServicesPage(){const tiers=[{icon:<Plane className="text-amber-500 shrink-0" size={32}/>,name:'Express Air Freight',desc:'Global expedited air freight with digital shipment records and priority handling.',specs:['Priority dispatch','Digital audit trails','Special handling']},{icon:<Ship className="text-amber-500 shrink-0" size={32}/>,name:'Ocean Cargo',desc:'High-volume sea freight distribution for containerized and consolidated cargo.',specs:['FCL & LCL','Port records','Shipment visibility']},{icon:<Truck className="text-amber-500 shrink-0" size={32}/>,name:'Last-Mile Distribution',desc:'Local delivery operations connecting depots to final destinations with tracking updates.',specs:['Driver tracking','Delivery events','Digital receipts']},{icon:<Warehouse className="text-amber-500 shrink-0" size={32}/>,name:'Warehousing',desc:'Organized storage and dispatch workflows for inventory and fulfillment operations.',specs:['Inventory workflows','Dispatch staging','Operational records']}];return <div className="max-w-6xl mx-auto px-4 py-16 space-y-12"><div className="text-center space-y-3 max-w-xl mx-auto"><span className="text-[10px] font-mono font-black text-[#155e8a] uppercase tracking-widest">Logify Network</span><h1 className="text-4xl font-display font-bold text-slate-900 dark:text-white">Logistics services</h1><p className="text-sm text-slate-500 dark:text-slate-400">Multi-modal logistics workflows designed around visibility and operational control.</p></div><div className="grid grid-cols-1 md:grid-cols-2 gap-6">{tiers.map((tier,i)=><div key={i} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl overflow-hidden shadow-sm p-7"><div className="w-12 h-12 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center">{tier.icon}</div><h3 className="mt-5 text-lg font-display font-bold text-slate-900 dark:text-white">{tier.name}</h3><p className="mt-2 text-sm text-slate-500 dark:text-slate-400 leading-6">{tier.desc}</p><div className="flex flex-wrap gap-2 mt-5">{tier.specs.map(s=><span key={s} className="text-[10px] bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 px-3 py-1.5 rounded-full font-mono font-bold text-slate-600 dark:text-slate-300">{s}</span>)}</div></div>)}</div></div>}
  function ContactPage(){const[submitting,setSubmitting]=useState(false),[sent,setSent]=useState(false);const submit=(e:React.FormEvent)=>{e.preventDefault();setSubmitting(true);setTimeout(()=>{setSubmitting(false);setSent(true)},1500)};return <div className="max-w-5xl mx-auto px-4 py-16 grid grid-cols-1 lg:grid-cols-2 gap-12"><div className="space-y-5 flex flex-col justify-center"><h1 className="text-4xl font-display font-bold text-slate-900 dark:text-white">Shipping support</h1><p className="text-sm text-slate-500 leading-7">Questions about shipments, logistics operations, integrations or billing? Contact the operations team.</p><div className="space-y-3 text-sm"><div className="flex gap-3"><Mail size={16}/>{settings.contactEmail}</div><div className="flex gap-3"><Phone size={16}/>{settings.contactPhone}</div></div></div><div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm">{sent?<div className="py-16 text-center"><ShieldCheck className="mx-auto text-emerald-500" size={40}/><h3 className="mt-4 font-display font-bold">Message received</h3><p className="mt-2 text-sm text-slate-500">Your inquiry has been queued for review.</p></div>:<form onSubmit={submit} className="space-y-4"><h3 className="font-display font-bold">Contact operations</h3><input required placeholder="Name" className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-4 py-3 outline-none"/><input required type="email" placeholder="Email" className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-4 py-3 outline-none"/><textarea required rows={5} placeholder="How can we help?" className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-4 py-3 outline-none resize-none"/><button disabled={submitting} className="w-full py-3 bg-amber-400 hover:bg-amber-300 disabled:opacity-50 text-[#0b1f33] font-black rounded-xl flex items-center justify-center gap-2">{submitting?<Loader2 size={14} className="animate-spin"/>:<Send size={14}/>}Send inquiry</button></form>}</div></div>}
  function MaintenancePage(){return <div className="flex-1 flex flex-col items-center justify-center min-h-[75vh] px-4 py-16 bg-[#0b1f33] text-neutral-300"><div className="max-w-md w-full bg-white/5 border border-white/10 rounded-3xl p-8 text-center"><div className="w-20 h-20 bg-amber-400/10 text-amber-400 rounded-2xl flex items-center justify-center mx-auto"><Lock size={36}/></div><h1 className="mt-6 text-xl font-display font-bold text-white">{settings.companyName||'Logify'} System Upgrade</h1><p className="mt-2 text-sm text-neutral-400 leading-6">Our logistics platform is undergoing a scheduled upgrade.</p></div></div>}

  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex flex-col font-sans transition-colors duration-300">
    {view!=='admin'&&settings.isSiteActive!==false&&<Navbar currentView={view} onNavigate={handleNavigate} user={user} onLogout={handleLogout} theme={theme} onToggleTheme={toggleTheme} settings={settings}/>}<div className="flex-1 flex flex-col">{authLoading?<div className="flex-1 flex flex-col items-center justify-center min-h-[70vh]"><Loader2 className="text-amber-500 animate-spin" size={36}/><p className="text-xs font-mono text-slate-400 mt-2">Authenticating credentials...</p></div>:settings.isSiteActive===false&&view!=='admin'&&view!=='auth'?<MaintenancePage/>:<>
      {view==='home'&&<><Hero onNavigate={handleNavigate} onSetTrackId={setTrackId}/><TrustCenter onNavigate={handleNavigate}/></>}
      {view==='track'&&<PublicTracker initialTrackId={trackId} onClearTrackId={()=>setTrackId('')} theme={theme} settings={settings}/>} {view==='send'&&<SendPackagePage settings={settings} onNavigate={handleNavigate} onSetTrackId={setTrackId}/>} {view==='pricing'&&<PricingPage settings={settings} onNavigate={handleNavigate}/>} {view==='about'&&<AboutPage onNavigate={handleNavigate}/>} {view==='quote'&&<QuoteCalculator settings={settings} onNavigate={handleNavigate} token={token}/>} {view==='services'&&<ServicesPage/>} {view==='contact'&&<ContactPage/>} {view==='auth'&&<AdminLogin onLoginSuccess={handleLoginSuccess} onNavigate={handleNavigate}/>} {view==='admin'&&user&&token&&<AdminPanel user={user} token={token} settings={settings} onUpdateSettings={setSettings} onLogout={handleLogout} theme={theme} onToggleTheme={toggleTheme}/>}</>}</div>
    {view!=='admin'&&<Footer onNavigate={handleNavigate} settings={settings}/>} {view!=='admin'&&settings.enableLiveChat!==false&&<PublicLiveChat companyName={settings.companyName||'Logify'}/>}</div>;
}
